In [17]:
import numpy as np
import pandas as pd

In [18]:
#carregando o dataframe

df = pd.read_csv('dados_conab/relatorio_preco_medio_mensal_2023.csv')

In [19]:
#pedindo 20 linhas aleatórias de exemplo dos dados

df.sample(20)

,Produto/Unidade,Nível de Comercialização,U.F.,01/2023,02/2023,03/2023,04/2023,05/2023,06/2023,07/2023,08/2023,09/2023,10/2023,11/2023,12/2023
148,ARROZ LONGO FINO BENEFICIADO TIPO 1 (2 kg),VAREJO,ES,"8,96","9,44","9,04","9,17","9,17","8,90","9,03","8,95","9,74","10,24","10,43","9,47"
1614,NaN,NaN,AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"47,63"
1704,NaN,NaN,SP,"138,97","162,37","177,94","181,77","192,25","194,05","186,14","181,42","151,19","147,20","144,78","147,81"
322,NaN,NaN,ES,"280,66","259,36","260,69","256,12","254,86","242,20","243,00",NaN,NaN,NaN,NaN,NaN
617,NaN,NaN,GO,"15,04","15,13","15,57","14,83","15,02","14,74","14,32","14,07","14,16","14,01",NaN,NaN
1995,UMBU FRUTO (kg),NaN,BA,"1,37","1,43","1,30",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,69"
602,NaN,NaN,PA,"213,92","235,96","201,36","195,25","209,67","231,68","220,33","206,40","187,33","183,08",NaN,NaN
228,NaN,NaN,PR,"74,06","73,09","68,22","42,00",NaN,NaN,NaN,NaN,"47,18","41,23","36,30","35,40"
1073,NaN,NaN,PI,"39,06","38,73","39,32","39,38","39,81","39,62","37,20",NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,ES,"9,71","9,59","9,03","9,73","9,60","8,81","8,11","7,44","6,84","6,72","6,53","5,18"
1249,NaN,NaN,MG,NaN,NaN,NaN,NaN,"1,50","1,50","1,50","1,50","1,50",NaN,NaN,NaN
252,NaN,NaN,RJ,"34,90","35,40","36,08","38,13","35,25","34,81","34,04","35,45","32,76","29,79","28,08","34,66"
453,CANOLA EM GRÃOS (60 kg),PRODUTOR,PR,"138,67","138,58","136,24",NaN,NaN,NaN,NaN,NaN,"110,67","111,00","113,95","115,07"
441,NaN,NaN,CE,"194,54","197,12","197,12","197,59","202,44","203,51","188,55","188,08","189,30","192,27","191,42","195,36"
701,CEVADA EM GRÃOS (60 kg),NaN,PR,"98,59","109,78","103,04","94,23",NaN,NaN,NaN,NaN,NaN,"74,64","73,16","79,27"
1686,NaN,NaN,RN,"14,97","15,27","18,11","18,02","17,92","18,43","17,76","17,05","15,86","15,23","15,56","15,47"
1006,NaN,NaN,RJ,"9,89","10,56","10,86","11,23","11,53","11,41","10,81","9,66","9,36","8,70","8,40","8,37"
989,NaN,VAREJO,AC,"6,79","6,82","6,84","6,81","6,84","7,06","7,20","7,22","7,22","7,27","7,28","7,24"
1222,NaN,NaN,MT,"162,50","150,83","142,83","130,00","118,26","111,59","108,33","87,17","87,38","90,00","95,00","96,19"
1998,NaN,NaN,RN,NaN,NaN,NaN,"0,98","0,98","0,98","0,98","0,98","0,98",NaN,NaN,NaN

In [20]:
#pedindo as primeiras 20 linhas

df.head(20)

,Produto/Unidade,Nível de Comercialização,U.F.,01/2023,02/2023,03/2023,04/2023,05/2023,06/2023,07/2023,08/2023,09/2023,10/2023,11/2023,12/2023
0,ABACATE (kg),ATACADO,RR,"6,83","6,67","6,83","7,00","7,00","6,00","6,00","6,60","7,00","7,00","7,00","7,00"
1,ABACAXI HAVAÍ (kg),PRODUTOR,PR,"1,85","2,31","2,30","2,30","2,30",NaN,NaN,NaN,NaN,NaN,"2,60","2,60"
2,ABACAXI (kg),ATACADO,RR,"2,59","2,65","2,79","6,00","8,00","4,50","4,50","4,95","5,00","7,50","7,00","7,50"
3,ABACAXI PÉROLA (6.50 kg),PRODUTOR,DF,"21,80","20,14","23,45","26,65","34,82","36,87","25,47","27,36","28,48","31,92","25,05","25,75"
4,ABACAXI PÉROLA (kg),NaN,AM,"3,81","3,75","3,75","3,90","4,00","4,25","4,02","3,94","4,27","4,25","4,51","4,23"
5,NaN,NaN,AP,"3,20","3,40","3,40","3,55","3,72","3,81","3,63","3,43","3,17",NaN,"3,42","3,25"
6,NaN,NaN,ES,"2,30","2,56","3,04","3,35","3,36","3,27","3,13","3,11","3,10","3,03","3,00","3,06"
7,NaN,NaN,RR,"2,17","2,13","2,24","3,62","3,93","4,14","3,90","5,74","6,50","6,50","6,70","6,52"
8,ABACAXI PÉROLA (t),NaN,BA,NaN,NaN,NaN,NaN,"2.000,00","1.977,27","2.050,00","2.204,35","2.295,24","2.325,00","2.300,00",NaN
9,NaN,NaN,SP,"1.587,50","1.744,44","1.862,50",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ABACAXI PÉROLA (un),ATACADO,MT,"3,96","4,41","4,52","4,41","4,47","4,39","4,91","5,00",NaN,NaN,NaN,NaN
11,NaN,PRODUTOR,AC,"3,45","3,45","3,45","3,46","3,93","4,00","4,03","4,05","4,05","4,05","4,05","4,05"
12,NaN,NaN,AL,"1,90","2,16",NaN,NaN,"2,40","2,81","2,66","2,89","2,74","3,15","3,27","3,59"
13,NaN,NaN,CE,"5,00","6,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5,00","5,00"
14,NaN,NaN,GO,"3,05","3,42","3,08","3,48","3,67","3,46","3,25","3,17","2,91","3,03","2,82","3,63"
15,NaN,NaN,MG,"1,93","2,68","2,60","3,45","3,43","2,81","2,85","3,44","3,52","3,60","3,69","3,20"
16,NaN,NaN,PA,"2,14","2,50","2,50","2,33","1,63","1,20","1,23","0,87","0,80","0,80","1,09","2,86"
17,NaN,NaN,PB,"2,36","2,36","2,53","2,53","2,53","2,53","2,53","2,53","2,37","2,50","2,50","2,57"
18,NaN,NaN,PE,"1,46","1,90","3,95","4,10","3,30","3,52","3,28","3,08","3,05","3,25","3,73","3,93"
19,NaN,NaN,RJ,"2,55","2,58","2,82","3,62","3,50","2,92","3,07","2,50","2,42","2,52","2,99","4,43"

In [21]:
#pedindo as últimas 20 linhas

df.tail(20)

,Produto/Unidade,Nível de Comercialização,U.F.,01/2023,02/2023,03/2023,04/2023,05/2023,06/2023,07/2023,08/2023,09/2023,10/2023,11/2023,12/2023
2009,NaN,NaN,SC,NaN,"1,40","1,39","1,38","1,38",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,UVA INDÚSTRIA NIÁGARA BRANCA (kg),NaN,MG,NaN,"6,36",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011,UVA INDÚSTRIA NIÁGARA (kg),NaN,SP,"4,54","4,15",NaN,NaN,"5,22","5,07","5,56","5,58","5,98","6,32","6,94","6,58"
2012,UVA MOSCATO (kg),NaN,RS,"2,13","2,13","2,13","2,13","1,89","1,89","1,89","1,89","1,89","1,89","1,89","1,89"
2013,UVA NIÁGARA (kg),NaN,RS,"1,58","1,58","1,58","1,58","1,40","1,40","1,40","1,40","1,40","1,40","1,40","1,40"
2014,VACA GORDA (@),NaN,TO,"244,46","221,85","207,12","209,71","192,51","174,68","185,56",NaN,NaN,NaN,NaN,NaN
2015,VACA GORDA (15 kg),NaN,DF,"277,75","267,00","240,65","225,50","223,00","197,09","188,33",NaN,NaN,NaN,NaN,NaN
2016,NaN,NaN,GO,"252,94","240,07","228,99","232,50","203,34","190,54","203,67",NaN,NaN,NaN,NaN,NaN
2017,NaN,NaN,MG,"238,85","243,21","237,23","241,77","216,44","195,29","195,68",NaN,NaN,NaN,NaN,NaN
2018,NaN,NaN,MS,"237,25","235,61","240,22","245,75","221,48","214,14","226,50",NaN,NaN,NaN,NaN,NaN
2019,NaN,NaN,MT,"233,75","228,28","223,74","229,08","208,89","186,85","189,34",NaN,NaN,NaN,NaN,NaN
2020,NaN,NaN,PA,"244,75","232,16","228,25","231,88","218,56","193,38","189,92",NaN,NaN,NaN,NaN,NaN
2021,NaN,NaN,PR,"257,83","252,30","251,87","254,04","231,54","210,84","221,00",NaN,NaN,NaN,NaN,NaN
2022,NaN,NaN,SE,"255,00","252,75","242,83","245,00","238,26","216,36","200,00",NaN,NaN,NaN,NaN,NaN
2023,NaN,NaN,SP,"258,31","256,87","255,37","250,75","224,06","208,60","214,59",NaN,NaN,NaN,NaN,NaN
2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026,Fonte: Companhia Nacional de Abastecimento - C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027,"As informações podem ser reproduzidas, desde q...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028,Proibida a comercialização das informações dis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#eliminar as últimas 5 linhas, que não tem dados

df = df.iloc[:-5]
df.tail(20)

,Produto/Unidade,Nível de Comercialização,U.F.,01/2023,02/2023,03/2023,04/2023,05/2023,06/2023,07/2023,08/2023,09/2023,10/2023,11/2023,12/2023
2004,NaN,NaN,PE,"5,00","4,83","5,42","4,94","4,49","3,90","4,13","4,40","4,69","5,00","5,97","6,38"
2005,UVA DE MESA NIÁGARA (kg),NaN,PR,"4,32","4,39","4,99","6,20","6,33","6,42","7,21","7,22","7,19","7,29","5,77","5,35"
2006,UVA GAMAY SAINT ROMAIN (kg),NaN,RS,"1,89","1,89","1,89","1,89","1,68","1,68","1,68","1,68","1,68","1,68","1,68","1,68"
2007,UVA INDÚSTRIA BORDÔ (kg),NaN,MG,NaN,"5,07",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008,UVA INDÚSTRIA ISABEL (kg),NaN,RS,"1,45","1,58","1,58","1,58","1,40","1,40","1,40","1,40","1,40","1,40","1,40","1,40"
2009,NaN,NaN,SC,NaN,"1,40","1,39","1,38","1,38",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,UVA INDÚSTRIA NIÁGARA BRANCA (kg),NaN,MG,NaN,"6,36",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011,UVA INDÚSTRIA NIÁGARA (kg),NaN,SP,"4,54","4,15",NaN,NaN,"5,22","5,07","5,56","5,58","5,98","6,32","6,94","6,58"
2012,UVA MOSCATO (kg),NaN,RS,"2,13","2,13","2,13","2,13","1,89","1,89","1,89","1,89","1,89","1,89","1,89","1,89"
2013,UVA NIÁGARA (kg),NaN,RS,"1,58","1,58","1,58","1,58","1,40","1,40","1,40","1,40","1,40","1,40","1,40","1,40"
2014,VACA GORDA (@),NaN,TO,"244,46","221,85","207,12","209,71","192,51","174,68","185,56",NaN,NaN,NaN,NaN,NaN
2015,VACA GORDA (15 kg),NaN,DF,"277,75","267,00","240,65","225,50","223,00","197,09","188,33",NaN,NaN,NaN,NaN,NaN
2016,NaN,NaN,GO,"252,94","240,07","228,99","232,50","203,34","190,54","203,67",NaN,NaN,NaN,NaN,NaN
2017,NaN,NaN,MG,"238,85","243,21","237,23","241,77","216,44","195,29","195,68",NaN,NaN,NaN,NaN,NaN
2018,NaN,NaN,MS,"237,25","235,61","240,22","245,75","221,48","214,14","226,50",NaN,NaN,NaN,NaN,NaN
2019,NaN,NaN,MT,"233,75","228,28","223,74","229,08","208,89","186,85","189,34",NaN,NaN,NaN,NaN,NaN
2020,NaN,NaN,PA,"244,75","232,16","228,25","231,88","218,56","193,38","189,92",NaN,NaN,NaN,NaN,NaN
2021,NaN,NaN,PR,"257,83","252,30","251,87","254,04","231,54","210,84","221,00",NaN,NaN,NaN,NaN,NaN
2022,NaN,NaN,SE,"255,00","252,75","242,83","245,00","238,26","216,36","200,00",NaN,NaN,NaN,NaN,NaN
2023,NaN,NaN,SP,"258,31","256,87","255,37","250,75","224,06","208,60","214,59",NaN,NaN,NaN,NaN,NaN

In [23]:
#preencher linhas em branco com o mesmo valor da última linha preenchida acima nas colunas Produto/Unidade e Nível de Comercialização

df['Produto/Unidade'] = df['Produto/Unidade'].ffill()
df['Nível de Comercialização'] = df['Nível de Comercialização'].ffill()

df['Produto/Unidade'].isnull().sum(), df['Nível de Comercialização'].isnull().sum()

(np.int64(0), np.int64(0))

In [24]:
#separa produto e unidade de medida e cria duas colunas. Pois, tem o mesmo produto em KG, toneladam, unidade, dúzia, litro... misturados na coluna Produto/Unidade
extracted = df['Produto/Unidade'].str.extract(r'^(.*?)\s*\(([^)]+)\)\s*$')
df['produto_nome'] = extracted[0].str.strip()
df['unidade'] = extracted[1].str.strip()
df.head(20)

,Produto/Unidade,Nível de Comercialização,U.F.,01/2023,02/2023,03/2023,04/2023,05/2023,06/2023,07/2023,08/2023,09/2023,10/2023,11/2023,12/2023,produto_nome,unidade
0,ABACATE (kg),ATACADO,RR,"6,83","6,67","6,83","7,00","7,00","6,00","6,00","6,60","7,00","7,00","7,00","7,00",ABACATE,kg
1,ABACAXI HAVAÍ (kg),PRODUTOR,PR,"1,85","2,31","2,30","2,30","2,30",NaN,NaN,NaN,NaN,NaN,"2,60","2,60",ABACAXI HAVAÍ,kg
2,ABACAXI (kg),ATACADO,RR,"2,59","2,65","2,79","6,00","8,00","4,50","4,50","4,95","5,00","7,50","7,00","7,50",ABACAXI,kg
3,ABACAXI PÉROLA (6.50 kg),PRODUTOR,DF,"21,80","20,14","23,45","26,65","34,82","36,87","25,47","27,36","28,48","31,92","25,05","25,75",ABACAXI PÉROLA,6.50 kg
4,ABACAXI PÉROLA (kg),PRODUTOR,AM,"3,81","3,75","3,75","3,90","4,00","4,25","4,02","3,94","4,27","4,25","4,51","4,23",ABACAXI PÉROLA,kg
5,ABACAXI PÉROLA (kg),PRODUTOR,AP,"3,20","3,40","3,40","3,55","3,72","3,81","3,63","3,43","3,17",NaN,"3,42","3,25",ABACAXI PÉROLA,kg
6,ABACAXI PÉROLA (kg),PRODUTOR,ES,"2,30","2,56","3,04","3,35","3,36","3,27","3,13","3,11","3,10","3,03","3,00","3,06",ABACAXI PÉROLA,kg
7,ABACAXI PÉROLA (kg),PRODUTOR,RR,"2,17","2,13","2,24","3,62","3,93","4,14","3,90","5,74","6,50","6,50","6,70","6,52",ABACAXI PÉROLA,kg
8,ABACAXI PÉROLA (t),PRODUTOR,BA,NaN,NaN,NaN,NaN,"2.000,00","1.977,27","2.050,00","2.204,35","2.295,24","2.325,00","2.300,00",NaN,ABACAXI PÉROLA,t
9,ABACAXI PÉROLA (t),PRODUTOR,SP,"1.587,50","1.744,44","1.862,50",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABACAXI PÉROLA,t
10,ABACAXI PÉROLA (un),ATACADO,MT,"3,96","4,41","4,52","4,41","4,47","4,39","4,91","5,00",NaN,NaN,NaN,NaN,ABACAXI PÉROLA,un
11,ABACAXI PÉROLA (un),PRODUTOR,AC,"3,45","3,45","3,45","3,46","3,93","4,00","4,03","4,05","4,05","4,05","4,05","4,05",ABACAXI PÉROLA,un
12,ABACAXI PÉROLA (un),PRODUTOR,AL,"1,90","2,16",NaN,NaN,"2,40","2,81","2,66","2,89","2,74","3,15","3,27","3,59",ABACAXI PÉROLA,un
13,ABACAXI PÉROLA (un),PRODUTOR,CE,"5,00","6,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5,00","5,00",ABACAXI PÉROLA,un
14,ABACAXI PÉROLA (un),PRODUTOR,GO,"3,05","3,42","3,08","3,48","3,67","3,46","3,25","3,17","2,91","3,03","2,82","3,63",ABACAXI PÉROLA,un
15,ABACAXI PÉROLA (un),PRODUTOR,MG,"1,93","2,68","2,60","3,45","3,43","2,81","2,85","3,44","3,52","3,60","3,69","3,20",ABACAXI PÉROLA,un
16,ABACAXI PÉROLA (un),PRODUTOR,PA,"2,14","2,50","2,50","2,33","1,63","1,20","1,23","0,87","0,80","0,80","1,09","2,86",ABACAXI PÉROLA,un
17,ABACAXI PÉROLA (un),PRODUTOR,PB,"2,36","2,36","2,53","2,53","2,53","2,53","2,53","2,53","2,37","2,50","2,50","2,57",ABACAXI PÉROLA,un
18,ABACAXI PÉROLA (un),PRODUTOR,PE,"1,46","1,90","3,95","4,10","3,30","3,52","3,28","3,08","3,05","3,25","3,73","3,93",ABACAXI PÉROLA,un
19,ABACAXI PÉROLA (un),PRODUTOR,RJ,"2,55","2,58","2,82","3,62","3,50","2,92","3,07","2,50","2,42","2,52","2,99","4,43",ABACAXI PÉROLA,un

In [25]:
#converte os preços de texto para número
meses = ['01/2023','02/2023','03/2023','04/2023','05/2023','06/2023',
         '07/2023','08/2023','09/2023','10/2023','11/2023','12/2023']

for col in meses:
    df[col] = (df[col].astype(str)
                       .str.replace('.', '', regex=False)
                       .str.replace(',', '.', regex=False)
                       .replace('nan', np.nan)
                       .astype(float))
df.info

<bound method DataFrame.info of                Produto/Unidade Nível de Comercialização U.F.  01/2023  \
0                 ABACATE (kg)                  ATACADO   RR     6.83
1           ABACAXI HAVAÍ (kg)                 PRODUTOR   PR     1.85
2                 ABACAXI (kg)                  ATACADO   RR     2.59
3     ABACAXI PÉROLA (6.50 kg)                 PRODUTOR   DF    21.80
4          ABACAXI PÉROLA (kg)                 PRODUTOR   AM     3.81
...                        ...                      ...  ...      ...
2019        VACA GORDA (15 kg)                 PRODUTOR   MT   233.75
2020        VACA GORDA (15 kg)                 PRODUTOR   PA   244.75
2021        VACA GORDA (15 kg)                 PRODUTOR   PR   257.83
2022        VACA GORDA (15 kg)                 PRODUTOR   SE   255.00
2023        VACA GORDA (15 kg)                 PRODUTOR   SP   258.31

      02/2023  03/2023  04/2023  05/2023  06/2023  07/2023  08/2023  09/2023  \
0        6.67     6.83     7.00     7.00     6.00     6.00     6.60     7.00
1        2.31     2.30     2.30     2.30      NaN      NaN      NaN      NaN
2        2.65     2.79     6.00     8.00     4.50     4.50     4.95     5.00
3       20.14    23.45    26.65    34.82    36.87    25.47    27.36    28.48
4        3.75     3.75     3.90     4.00     4.25     4.02     3.94     4.27
...       ...      ...      ...      ...      ...      ...      ...      ...
2019   228.28   223.74   229.08   208.89   186.85   189.34      NaN      NaN
2020   232.16   228.25   231.88   218.56   193.38   189.92      NaN      NaN
2021   252.30   251.87   254.04   231.54   210.84   221.00      NaN      NaN
2022   252.75   242.83   245.00   238.26   216.36   200.00      NaN      NaN
2023   256.87   255.37   250.75   224.06   208.60   214.59      NaN      NaN

      10/2023  11/2023  12/2023    produto_nome  unidade
0        7.00     7.00     7.00         ABACATE       kg
1         NaN     2.60     2.60   ABACAXI HAVAÍ       kg
2        7.50     7.00     7.50         ABACAXI       kg
3       31.92    25.05    25.75  ABACAXI PÉROLA  6.50 kg
4        4.25     4.51     4.23  ABACAXI PÉROLA       kg
...       ...      ...      ...             ...      ...
2019      NaN      NaN      NaN      VACA GORDA    15 kg
2020      NaN      NaN      NaN      VACA GORDA    15 kg
2021      NaN      NaN      NaN      VACA GORDA    15 kg
2022      NaN      NaN      NaN      VACA GORDA    15 kg
2023      NaN      NaN      NaN      VACA GORDA    15 kg

[2024 rows x 17 columns]>

In [26]:
#transforma as 12 colunas de mês em 2 colunas: mes_ano e preco_medio(daquele mês)

df_novo = df.melt(
    id_vars=['produto_nome', 'unidade', 'Nível de Comercialização', 'U.F.'],
    value_vars=meses,
    var_name='mes_ano',
    value_name='preco_medio'
)
df_novo.head(20)

,produto_nome,unidade,Nível de Comercialização,U.F.,mes_ano,preco_medio
0,ABACATE,kg,ATACADO,RR,01/2023,6.83
1,ABACAXI HAVAÍ,kg,PRODUTOR,PR,01/2023,1.85
2,ABACAXI,kg,ATACADO,RR,01/2023,2.59
3,ABACAXI PÉROLA,6.50 kg,PRODUTOR,DF,01/2023,21.80
4,ABACAXI PÉROLA,kg,PRODUTOR,AM,01/2023,3.81
5,ABACAXI PÉROLA,kg,PRODUTOR,AP,01/2023,3.20
6,ABACAXI PÉROLA,kg,PRODUTOR,ES,01/2023,2.30
7,ABACAXI PÉROLA,kg,PRODUTOR,RR,01/2023,2.17
8,ABACAXI PÉROLA,t,PRODUTOR,BA,01/2023,NaN
9,ABACAXI PÉROLA,t,PRODUTOR,SP,01/2023,1587.50
10,ABACAXI PÉROLA,un,ATACADO,MT,01/2023,3.96
11,ABACAXI PÉROLA,un,PRODUTOR,AC,01/2023,3.45
12,ABACAXI PÉROLA,un,PRODUTOR,AL,01/2023,1.90
13,ABACAXI PÉROLA,un,PRODUTOR,CE,01/2023,5.00
14,ABACAXI PÉROLA,un,PRODUTOR,GO,01/2023,3.05
15,ABACAXI PÉROLA,un,PRODUTOR,MG,01/2023,1.93
16,ABACAXI PÉROLA,un,PRODUTOR,PA,01/2023,2.14
17,ABACAXI PÉROLA,un,PRODUTOR,PB,01/2023,2.36
18,ABACAXI PÉROLA,un,PRODUTOR,PE,01/2023,1.46
19,ABACAXI PÉROLA,un,PRODUTOR,RJ,01/2023,2.55

In [27]:
regiao_map = {
    'AC':'Norte','AP':'Norte','AM':'Norte','PA':'Norte','RO':'Norte','RR':'Norte','TO':'Norte',
    'AL':'Nordeste','BA':'Nordeste','CE':'Nordeste','MA':'Nordeste','PB':'Nordeste',
    'PE':'Nordeste','PI':'Nordeste','RN':'Nordeste','SE':'Nordeste',
    'DF':'Centro-Oeste','GO':'Centro-Oeste','MT':'Centro-Oeste','MS':'Centro-Oeste',
    'ES':'Sudeste','MG':'Sudeste','RJ':'Sudeste','SP':'Sudeste',
    'PR':'Sul','RS':'Sul','SC':'Sul'
}
df_regiao = pd.DataFrame(list(regiao_map.items()), columns=['U.F.', 'regiao'])

linhas_antes = len(df_novo)
df_novo = df_novo.merge(df_regiao, on='U.F.', how='left')
print(linhas_antes, len(df_novo))  # confere se bateu — sem duplicar linha

24288 24288

In [28]:
df_novo.head(20)

,produto_nome,unidade,Nível de Comercialização,U.F.,mes_ano,preco_medio,regiao
0,ABACATE,kg,ATACADO,RR,01/2023,6.83,Norte
1,ABACAXI HAVAÍ,kg,PRODUTOR,PR,01/2023,1.85,Sul
2,ABACAXI,kg,ATACADO,RR,01/2023,2.59,Norte
3,ABACAXI PÉROLA,6.50 kg,PRODUTOR,DF,01/2023,21.80,Centro-Oeste
4,ABACAXI PÉROLA,kg,PRODUTOR,AM,01/2023,3.81,Norte
5,ABACAXI PÉROLA,kg,PRODUTOR,AP,01/2023,3.20,Norte
6,ABACAXI PÉROLA,kg,PRODUTOR,ES,01/2023,2.30,Sudeste
7,ABACAXI PÉROLA,kg,PRODUTOR,RR,01/2023,2.17,Norte
8,ABACAXI PÉROLA,t,PRODUTOR,BA,01/2023,NaN,Nordeste
9,ABACAXI PÉROLA,t,PRODUTOR,SP,01/2023,1587.50,Sudeste
10,ABACAXI PÉROLA,un,ATACADO,MT,01/2023,3.96,Centro-Oeste
11,ABACAXI PÉROLA,un,PRODUTOR,AC,01/2023,3.45,Norte
12,ABACAXI PÉROLA,un,PRODUTOR,AL,01/2023,1.90,Nordeste
13,ABACAXI PÉROLA,un,PRODUTOR,CE,01/2023,5.00,Nordeste
14,ABACAXI PÉROLA,un,PRODUTOR,GO,01/2023,3.05,Centro-Oeste
15,ABACAXI PÉROLA,un,PRODUTOR,MG,01/2023,1.93,Sudeste
16,ABACAXI PÉROLA,un,PRODUTOR,PA,01/2023,2.14,Norte
17,ABACAXI PÉROLA,un,PRODUTOR,PB,01/2023,2.36,Nordeste
18,ABACAXI PÉROLA,un,PRODUTOR,PE,01/2023,1.46,Nordeste
19,ABACAXI PÉROLA,un,PRODUTOR,RJ,01/2023,2.55,Sudeste

## Análise 1: Qual produto apresentou o maior aumento percentual entre janeiro e dezembro de 2023?

In [1]:
# Filtrar apenas janeiro e dezembro
df_jan = df_novo[df_novo['mes_ano'] == '01/2023']
df_dez = df_novo[df_novo['mes_ano'] == '12/2023']

# Agrupar por produto e unidade para ter o preço médio nacional em cada mês
preco_jan = df_jan.groupby(['produto_nome', 'unidade'])['preco_medio'].mean().reset_index(name='preco_jan')
preco_dez = df_dez.groupby(['produto_nome', 'unidade'])['preco_medio'].mean().reset_index(name='preco_dez')

# Juntar as duas tabelas
variacao = pd.merge(preco_jan, preco_dez, on=['produto_nome', 'unidade'])

# Calcular a variação percentual
variacao['variacao_pct'] = (variacao['preco_dez'] - variacao['preco_jan']) / variacao['preco_jan'] * 100

# Produto com maior aumento
top_produto = variacao.loc[variacao['variacao_pct'].idxmax()]
print(f"Produto com maior aumento: {top_produto['produto_nome']} ({top_produto['unidade']})")
print(f"Aumento de {top_produto['variacao_pct']:.2f}% (de R${top_produto['preco_jan']:.2f} para R${top_produto['preco_dez']:.2f})")

# Visualizar os 10 maiores aumentos
import matplotlib.pyplot as plt
top10 = variacao.nlargest(10, 'variacao_pct')
plt.figure(figsize=(10,6))
plt.barh(top10['produto_nome'] + ' (' + top10['unidade'] + ')', top10['variacao_pct'])
plt.xlabel('Variação percentual (%)')
plt.title('Top 10 produtos com maior aumento de preço (jan → dez 2023)')
plt.tight_layout()
plt.show()

NameError: name 'df_novo' is not defined

## Análise 2: Qual região teve o preço médio mais alto para "ABACAXI PÉROLA (kg)" em 2023?

In [ ]:
# Filtrar o produto específico
abacaxi = df_novo[(df_novo['produto_nome'] == 'ABACAXI PÉROLA') & (df_novo['unidade'] == 'kg')]

# Calcular a média anual por região
media_regiao = abacaxi.groupby('regiao')['preco_medio'].mean().reset_index()
media_regiao = media_regiao.sort_values('preco_medio', ascending=False)

# Exibir
print("Preço médio anual da ABACAXI PÉROLA (kg) por região:")
print(media_regiao)

# Região com maior preço
maior = media_regiao.iloc[0]
print(f"\nRegião com maior preço médio: {maior['regiao']} (R${maior['preco_medio']:.2f})")

# Gráfico de barras
plt.figure(figsize=(8,5))
plt.bar(media_regiao['regiao'], media_regiao['preco_medio'], color='orange')
plt.ylabel('Preço médio (R$)')
plt.title('Preço médio da ABACAXI PÉROLA (kg) por região em 2023')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

## Análise 3: Existe sazonalidade no preço do ABACATE (kg) ao longo dos meses?

In [ ]:
# Filtrar abacate em kg
abacate = df_novo[(df_novo['produto_nome'] == 'ABACATE') & (df_novo['unidade'] == 'kg')]

# Calcular a média nacional por mês (considerando todas as UFs e níveis)
media_mensal = abacate.groupby('mes_ano')['preco_medio'].mean().reset_index()

# Ordenar cronologicamente (já que mes_ano está como string, converter para data)
media_mensal['mes_num'] = pd.to_datetime(media_mensal['mes_ano'], format='%m/%Y').dt.month
media_mensal = media_mensal.sort_values('mes_num')

# Gráfico de linha
plt.figure(figsize=(10,5))
plt.plot(media_mensal['mes_ano'], media_mensal['preco_medio'], marker='o', linestyle='-')
plt.ylabel('Preço médio nacional (R$)')
plt.xlabel('Mês')
plt.title('Variação mensal do preço do ABACATE (kg) em 2023')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# Estatísticas
print("Preço médio por mês:")
print(media_mensal)
print(f"\nMês com maior preço: {media_mensal.loc[media_mensal['preco_medio'].idxmax(), 'mes_ano']} (R${media_mensal['preco_medio'].max():.2f})")
print(f"Mês com menor preço: {media_mensal.loc[media_mensal['preco_medio'].idxmin(), 'mes_ano']} (R${media_mensal['preco_medio'].min():.2f})")

## Análise 4: O preço do arroz no atacado é diferente do varejo?

In [ ]:
# Filtrar produtos que contenham "ARROZ" (exemplo: ARROZ LONGO FINO...) e unidade 'kg'
arroz = df_novo[(df_novo['produto_nome'].str.contains('ARROZ', case=False)) & (df_novo['unidade'] == 'kg')]

# Calcular média por nível de comercialização
media_nivel = arroz.groupby('Nível de Comercialização')['preco_medio'].mean().reset_index()

print("Preço médio do arroz (kg) por nível de comercialização:")
print(media_nivel)

# Gráfico
plt.figure(figsize=(8,5))
plt.bar(media_nivel['Nível de Comercialização'], media_nivel['preco_medio'], color=['green', 'blue', 'red'])
plt.ylabel('Preço médio (R$)')
plt.xlabel('Nível de Comercialização')
plt.title('Comparação de preços do arroz (kg) por canal')
for i, row in media_nivel.iterrows():
    plt.text(row['Nível de Comercialização'], row['preco_medio']+0.5, f'R${row["preco_medio"]:.2f}', ha='center')
plt.tight_layout()
plt.show()

# Comparação direta (atacado vs varejo)
if 'ATACADO' in media_nivel['Nível de Comercialização'].values and 'VAREJO' in media_nivel['Nível de Comercialização'].values:
    preco_atacado = media_nivel[media_nivel['Nível de Comercialização'] == 'ATACADO']['preco_medio'].values[0]
    preco_varejo = media_nivel[media_nivel['Nível de Comercialização'] == 'VAREJO']['preco_medio'].values[0]
    diferenca_pct = (preco_varejo - preco_atacado) / preco_atacado * 100
    print(f"\nO varejo é {diferenca_pct:.2f}% mais caro que o atacado.")

## Análise 5: Quais foram os 5 meses com maior preço médio geral (todos os produtos e UFs)?

In [ ]:
# Média geral simples por mês (sem ponderação por volume de vendas – apenas a média dos preços registrados)
media_geral_mes = df_novo.groupby('mes_ano')['preco_medio'].mean().reset_index()

# Ordenar e pegar os 5 maiores
top5_meses = media_geral_mes.nlargest(5, 'preco_medio')

print("5 meses com maior preço médio geral (todos os produtos):")
print(top5_meses)

# Gráfico de barras
plt.figure(figsize=(8,5))
plt.bar(top5_meses['mes_ano'], top5_meses['preco_medio'], color='purple')
plt.ylabel('Preço médio geral (R$)')
plt.xlabel('Mês')
plt.title('Top 5 meses com maior preço médio em 2023')
for i, row in top5_meses.iterrows():
    plt.text(row['mes_ano'], row['preco_medio']+0.5, f'R${row["preco_medio"]:.2f}', ha='center')
plt.tight_layout()
plt.show()